degbugging

diff --git a/.github/workflows/deploy_nrec.yml b/.github/workflows/deploy_nrec.yml
--- a/.github/workflows/deploy_nrec.yml
+++ b/.github/workflows/deploy_nrec.yml
@@ -64,13 +64,18 @@ jobs:
             ssh_key="${{ secrets.SSH_PRIVATE_KEY }}"
             echo "${ssh_key}" > ~/.ssh/id_rsa
             chmod 600 ~/.ssh/id_rsa
-                        
+
         shell: bash
       - name: Scan host keys for host
         run: |
-            host="${{ secrets.HOST }}"       
-            ssh-keyscan -H "${host}" >> ~/.ssh/known_hosts || {
-              echo "Failed to scan host keys for ${host}"
+            host="${{ secrets.HOST }}"
+            for i in {1..5}; do
+              echo "Attempting to scan host keys for ${host}, try #${i}"
+              ssh-keyscan -T 10 -H "${host}" >> ~/.ssh/known_hosts 2>&1 && break
+              echo "Scan failed, retrying after 5s"
+              sleep 5
+            done || {
+              echo "Failed to scan host keys for ${host} after 5 attempts"
               exit 1
             }
         shell: bash
