Test for http 200

diff --git a/.github/workflows/deploy_nrec.yml b/.github/workflows/deploy_nrec.yml
--- a/.github/workflows/deploy_nrec.yml
+++ b/.github/workflows/deploy_nrec.yml
@@ -7,7 +7,10 @@ on:
   # Triggers the workflow on push or pull request events but only for the "main" branch
   push:
     branches: [ "main" ]
-    
+
+  #Every day at 1am
+  schedule:
+    - cron: '0 1 * * *'
 
   # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
@@ -107,6 +110,15 @@ jobs:
     steps:
       - name: Verify CHAP core
         run: |
-          curl -s -o /dev/null -w "200" http://${{ secrets.HOST }}/docs
+          status_code=$(curl -s -o /dev/null -w "%{http_code}" http://${{ secrets.HOST }}/docs)
+
+          # Check if the status code is 200
+          if [ "$status_code" -eq 200 ]; then
+              echo "Success: Returned status code 200"
+          else
+              echo "Failed: Returned status code $status_code"
+              exit 1
+          fi
+
         shell: bash
 
