syntax

diff --git a/.github/workflows/deploy_nrec.yml b/.github/workflows/deploy_nrec.yml
--- a/.github/workflows/deploy_nrec.yml
+++ b/.github/workflows/deploy_nrec.yml
@@ -69,16 +69,16 @@ jobs:
         # - name: Scan host keys for host
       - name: Attempting to scan host keys for
         run: |
-          host="${{ secrets.HOST }}"
-          for i in {1..50}; do
-            echo "Attempting to scan host keys for ${host}, try #${i}"
-            ssh-keyscan -T 10 -H "${host}" >> ~/.ssh/known_hosts 2>&1 && break
-            echo "Scan failed, retrying after 2s"
-            sleep 2
-          done || {
-            echo "Failed to scan host keys for ${host} after 50 attempts"
-            exit 1
-          } 
+           host="${{ secrets.HOST }}"
+           for i in {1..50}; do
+             echo "Attempting to scan host keys for ${host}, try #${i}"
+             ssh-keyscan -T 10 -H "${host}" >> ~/.ssh/known_hosts 2>&1 && break
+             echo "Scan failed, retrying after 2s"
+             sleep 2
+           done || {
+             echo "Failed to scan host keys for ${host} after 50 attempts"
+             exit 1
+           } 
         shell: bash
         
         #Copty the infrastructure folder to the remote server
