ssh with ssh-action

diff --git a/.github/workflows/deploy_nrec.yml b/.github/workflows/deploy_nrec.yml
--- a/.github/workflows/deploy_nrec.yml
+++ b/.github/workflows/deploy_nrec.yml
@@ -48,37 +48,46 @@ jobs:
     # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
       # This was added due to this error: https://stackoverflow.com/questions/20840012/ssh-remote-host-identification-has-changed
-      - name: Remove all keys belonging to hostname from a known_hosts file
-        run: |
-          ssh-keygen -R ${{ secrets.HOST }} || true
-        shell: bash
-      - name: Clone CHAP Core repo
-        run: |
-          git clone https://github.com/dhis2-chap/chap-core-infrastructure-example.git infrastructure
-        shell: bash
-      # Runs a single command using the runners shell
-      - name: Write the SSH key to a file on GitHub Actions
-        run: | 
-            set -e
-            mkdir -p ~/.ssh
-            ssh_key="${{ secrets.SSH_PRIVATE_KEY }}"
-            echo "${ssh_key}" > ~/.ssh/id_rsa
-            chmod 600 ~/.ssh/id_rsa
+    #  - name: Remove all keys belonging to hostname from a known_hosts file
+    #    run: |
+    #      ssh-keygen -R ${{ secrets.HOST }} || true
+    #    shell: bash
+    #  - name: Clone CHAP Core repo
+    #    run: |
+    #      git clone https://github.com/dhis2-chap/chap-core-infrastructure-example.git infrastructure
+    #    shell: bash
+    #  # Runs a single command using the runners shell
+    #  - name: Write the SSH key to a file on GitHub Actions
+    #    run: | 
+    #        set -e
+    #        mkdir -p ~/.ssh
+    #        ssh_key="${{ secrets.SSH_PRIVATE_KEY }}"
+    #        echo "${ssh_key}" > ~/.ssh/id_rsa
+    #        chmod 600 ~/.ssh/id_rsa
 
-        shell: bash
-      - name: Scan host keys for host
-        run: |
-            host="${{ secrets.HOST }}"
-            for i in {1..5}; do
-              echo "Attempting to scan host keys for ${host}, try #${i}"
-              ssh-keyscan -T 10 -H "${host}" >> ~/.ssh/known_hosts 2>&1 && break
-              echo "Scan failed, retrying after 5s"
-              sleep 5
-            done || {
-              echo "Failed to scan host keys for ${host} after 5 attempts"
-              exit 1
-            }
-        shell: bash
+    #    shell: bash
+    #  - name: Scan host keys for host
+    #    run: |
+    #        host="${{ secrets.HOST }}"
+    #        for i in {1..5}; do
+    #          echo "Attempting to scan host keys for ${host}, try #${i}"
+    #          ssh-keyscan -T 10 -H "${host}" >> ~/.ssh/known_hosts 2>&1 && break
+    #          echo "Scan failed, retrying after 5s"
+    #          sleep 5
+    #        done || {
+    #          echo "Failed to scan host keys for ${host} after 5 attempts"
+    #          exit 1
+    #        }
+    #    shell: bash
+      - name: multiple command
+        uses: appleboy/ssh-action@v1.2.0
+        with:
+          host: ${{ secrets.HOST }}
+          username: ${{ secrets.SSH_USERNAME }}
+          key: ${{ secrets.SSH_PRIVATE_KEY }}
+          script: |
+            mkdir test
+#            scp -i ~/.ssh/id_rsa -r infrastructure/ ${{ secrets.SSH_USERNAME }}:/home/ubuntu/chap-core
 
       - name: Copy files to remote server
         run: |
