Debug rare error

diff --git a/.github/workflows/deploy_nrec.yml b/.github/workflows/deploy_nrec.yml
--- a/.github/workflows/deploy_nrec.yml
+++ b/.github/workflows/deploy_nrec.yml
@@ -10,34 +10,34 @@ on:
 
 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
-  resetInstance:
-    name: Reset CHAP core instance on NREC
-    runs-on: ubuntu-latest
-    steps:
-        #Install OpenStack CLI
-      - name: Install OpenStack CLI
-        run: |
-          sudo apt-get update
-          sudo snap install openstackclients
-          sudo apt  install python3-openstackclient
-        shell: bash
+ # resetInstance:
+ #   name: Reset CHAP core instance on NREC
+ #   runs-on: ubuntu-latest
+ #   steps:
+ #       #Install OpenStack CLI
+ #     - name: Install OpenStack CLI
+ #       run: |
+ #         sudo apt-get update
+ #         sudo snap install openstackclients
+ #         sudo apt  install python3-openstackclient
+ #       shell: bash
 
-        #This rebuilds the instance using OpenStack CLI
-      - name: Rebuild CHAP instance
-        run: |
-          export OS_USERNAME=${{ secrets.OPENSTACK_USERNAME }}
-          export OS_PROJECT_NAME=${{ secrets.OPENSTACK_PROJECT_NAME }}
-          export OS_PASSWORD=${{ secrets.OPENSTACK_PASSWORD }}
-          export OS_AUTH_URL=https://api.nrec.no:5000/v3
-          export OS_IDENTITY_API_VERSION=3
-          export OS_USER_DOMAIN_NAME=dataporten
-          export OS_PROJECT_DOMAIN_NAME=dataporten
-          export OS_REGION_NAME=osl
-          export OS_INTERFACE=public
-          export OS_NO_CACHE=1
-          
-          openstack server rebuild --wait --image 97397a31-2517-4eb8-b66f-1d50c00dbb77 chap
-        shell: bash
+ #       #This rebuilds the instance using OpenStack CLI
+ #     - name: Rebuild CHAP instance
+ #       run: |
+ #         export OS_USERNAME=${{ secrets.OPENSTACK_USERNAME }}
+ #         export OS_PROJECT_NAME=${{ secrets.OPENSTACK_PROJECT_NAME }}
+ #         export OS_PASSWORD=${{ secrets.OPENSTACK_PASSWORD }}
+ #         export OS_AUTH_URL=https://api.nrec.no:5000/v3
+ #         export OS_IDENTITY_API_VERSION=3
+ #         export OS_USER_DOMAIN_NAME=dataporten
+ #         export OS_PROJECT_DOMAIN_NAME=dataporten
+ #         export OS_REGION_NAME=osl
+ #         export OS_INTERFACE=public
+ #         export OS_NO_CACHE=1
+ #         
+ #         openstack server rebuild --wait --image 97397a31-2517-4eb8-b66f-1d50c00dbb77 chap
+ #       shell: bash
       
   deployChap:
     needs: resetInstance
@@ -58,11 +58,28 @@ jobs:
       # Runs a single command using the runners shell
       - name: Write the SSH key to a file on GitHub Actions
         run: | 
-          set -e
-          mkdir -p ~/.ssh
-          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
-          chmod 600 ~/.ssh/id_rsa
-          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts
+            mkdir -p ~/.ssh
+            ssh_key="${{ secrets.SSH_PRIVATE_KEY }}"
+            if [[ -z "${ssh_key// }" ]]; then
+              echo "SSH key is not set or empty."
+              exit 1
+            fi
+            echo "${ssh_key}" > ~/.ssh/id_rsa
+            chmod 600 ~/.ssh/id_rsa
+            
+            host="${{ secrets.HOST }}"
+            if [[ -z "${host// }" ]]; then
+              echo "Host is not set or empty."
+              exit 1
+            fi
+            ssh-keyscan -H "${host}" >> ~/.ssh/known_hosts || {
+              echo "Failed to scan host keys for ${host}"
+              exit 1
+            }
+#          mkdir -p ~/.ssh
+#          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
+#          chmod 600 ~/.ssh/id_rsa
+#          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts
         #Copty the infras
       - name: Copy files to remote server
         run: |
